Numpy

In [ ]:
 import numpy as np

In [3]:
 import numpy as np  
oneDarray = np.array([1,2,3,4,5])
print(oneDarray)

[1 2 3 4 5]


In [6]:
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [7]:
twoDarray[1]

array([4, 5, 6])

In [8]:
threeDarray = np.array([[[1,2,3],[-1,-2,-3]],[[4,5,6],[-4,-5,-6]]])
threeDarray

array([[[ 1,  2,  3],
        [-1, -2, -3]],

       [[ 4,  5,  6],
        [-4, -5, -6]]])

In [9]:
threeDarray[0]

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [12]:
zeroArrays = np.zeros(10)
zeroArrays = zeroArrays.astype(int)
zeroArrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
onesArray = np.ones(10)
onesArray = onesArray.astype(int)
onesArray

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
fullArray = np.full(10,2)
fullArray 

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix + 2)

[[3 4 5]
 [6 7 8]]


In [16]:
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [17]:
print(matrix ** 2)

[[ 1  4  9]
 [16 25 36]]


In [18]:
t = matrix.T
t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
matrix1 = np.array([[-1,-2,-3], [-4,-5,-6], [0,0,0]])
matrix2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
M = np.matmul(matrix1 , matrix2)
M

array([[-30, -36, -42],
       [-66, -81, -96],
       [  0,   0,   0]])

In [21]:
np.min(matrix)

1

In [22]:
np.max(matrix)

6

In [23]:
np.sum(matrix)

21

In [24]:
np.mean(matrix)

3.5

In [25]:
np.std(matrix)

1.707825127659933

In [27]:
np.median(matrix)

3.5